networks:
  dbwebb:

services:
  server:
    image: davidallert/scooter-server:1.0
    container_name: "scootersystemserver"
    ports:
      - "8585:8585"
    networks:
      dbwebb:
    restart:
      "always"
  client:
    image: mobn23/scooters-system-client:1.0
    container_name: "scootersystemclient"
    networks:
      dbwebb:
    links:
      - "server:scootersystemserver"