---
build:
  nodes:
    analysis:
      image: default-jammy
      environment:
        variables:
          NODE_VERSION: 20.12.0
      dependencies:
        before:
          - nvm install $NODE_VERSION
          - nvm use $NODE_VERSION
          - npm install
      tests:
        override:
          - npm run test
          - npm run test:jest

filter:
  paths:
    # Specify directories that Scrutinizer will analyze.
    - datamodels/
    - db/
    - graphql/
    - routes/
    - test/
  excluded_paths:
    - node_modules/
