---
build:
  nodes:
    analysis:
      image: default-jammy
      environment:
        variables:
          NODE_VERSION: 20.12.0
          NODE_ENV: "test"
          JWTSECRET: "elscootervteam3"
      dependencies:
        before:
          - nvm install $NODE_VERSION
          - nvm use $NODE_VERSION
          - npm install

filter:
    paths:
        # Specify directories that Scrutinizer will analyze.
        - datamodels/
        - db/
        - graphql/
        - routes/
        - tests/
    excluded_paths:
        - node_modules/

checks:
  javascript: true