name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: [6.0, 7.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    # Make sure 'npm install' runs from the 'server' folder
    - run: npm install  # Clean install.
      working-directory: ./server  # Make sure it's in the 'server' directory

    # Run the build step inside the 'server' directory
    - run: npm run build --if-present
      working-directory: ./server  # Point to the 'server' directory

    # Run tests in the 'server' directory
    - run: npm test
      working-directory: ./server
      env:
        JWTSECRET: ${{ secrets.JWTSECRET }}
        PORT: 8585
        NODE_ENV: test
        DB_PASS: ${{ secrets.DB_PASS }}
        GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_OAUTH_URL: ${{ secrets.GOOGLE_OAUTH_URL }}
        GOOGLE_ACCESS_TOKEN_URL: ${{ vars.GOOGLE_ACCESS_TOKEN_URL }}
        GOOGLE_TOKEN_INFO_URL: ${{ vars.GOOGLE_TOKEN_INFO_URL }}
        OAUTHSECRET: ${{ secrets.OAUTHSECRET }}
